// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUj4ztJZ4oTCSW4ESycKebc_doa12o2S8',
    appId: '1:1003659845123:web:20d1b36660baa20e55b836',
    messagingSenderId: '1003659845123',
    projectId: 'ecommerce-8beb9',
    authDomain: 'ecommerce-8beb9.firebaseapp.com',
    storageBucket: 'ecommerce-8beb9.appspot.com',
    measurementId: 'G-J2PBVJ6EK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeJFkQk7x8yXq-DLgV8LZonaWAWiWse88',
    appId: '1:1003659845123:android:f79912644c71b46555b836',
    messagingSenderId: '1003659845123',
    projectId: 'ecommerce-8beb9',
    storageBucket: 'ecommerce-8beb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzjxM-SHyumb9jDX2Z-oHM8Iv4GedcAqo',
    appId: '1:1003659845123:ios:987aa9d23229cd0955b836',
    messagingSenderId: '1003659845123',
    projectId: 'ecommerce-8beb9',
    storageBucket: 'ecommerce-8beb9.appspot.com',
    iosClientId: '1003659845123-4l6gjas4qgsmou7frtl6lvb824b7gp13.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzjxM-SHyumb9jDX2Z-oHM8Iv4GedcAqo',
    appId: '1:1003659845123:ios:987aa9d23229cd0955b836',
    messagingSenderId: '1003659845123',
    projectId: 'ecommerce-8beb9',
    storageBucket: 'ecommerce-8beb9.appspot.com',
    iosClientId: '1003659845123-4l6gjas4qgsmou7frtl6lvb824b7gp13.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
